/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import java.sql.ResultSet;
import Modelo.conexionSql;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author karla
 */
public class Ncionalidad extends javax.swing.JPanel {
 private Registro registro;  // Referencia a la instancia de Registro

    public void setRegistro(Registro registro) {
        this.registro = registro;  // Establecer la referencia a la instancia de Registro
    }
   
    
    public Ncionalidad() {
        initComponents();
        Mostrar();
        addCheckBox(2, jTable1);
    }
    
     public void Mostrar(){
        //Definir un modelo de datos para la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        //Agregar columnas o encabezado de la tabla
        modelo.setColumnIdentifiers(new Object[] {"IdNacionalidad", "Nacionalidad", "Select"});
        //Hacer select a la base de datos
        try{
            Statement statement = conexionSql.getConexion().createStatement();
            ResultSet rs = statement.executeQuery("select * from tbNacionalidades");
            
            //Recorrer los resultados
            while(rs.next()){
                modelo.addRow(new Object[] {rs.getInt("IdNacionalidad"), rs.getString("Nacionalidad")} );
             
            }
            jTable1.setModel(modelo);
        }catch(SQLException ex){
            System.out.println(ex.toString());
        }
    }
     
     //metodo para poner los checkbox en las columnas
     public void addCheckBox(int column, JTable table)
    {
        //se crea una estancia de tablecolum para obtener modelo y numero de columna
        TableColumn tc = table.getColumnModel().getColumn(column);
        //lo pasamos a booleanos para poner obtener info
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
        
    }

    public boolean IsSelected(int row, int column, JTable table)
    {    
        return table.getValueAt(row, column) != null;                       
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(70, 70, 70));
        setPreferredSize(new java.awt.Dimension(950, 570));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setText("Agregar");
        jPanel1.add(jLabel1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 90, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
//        if (registro != null) {
//            // Obtener los idiomas seleccionados de la tabla
//            for (int row = 0; row < jTable1.getRowCount(); row++) {
//                boolean isSelected = IsSelected(row, 2, jTable1);  // Verificar si la casilla está seleccionada
//                if (isSelected) {
//                    Boolean idioma = (Boolean) jTable1.getValueAt(row, 2);  // Obtener el valor de idioma seleccionado
//                    registro.agregarIdiomaSeleccionado(idioma);  // Utilizar la referencia a registro para agregar el idioma seleccionado
//                    System.out.println("funciona beybi");
//                }
//            }
//        } else {
//            System.out.println("La referencia 'registro' no se ha establecido correctamente.");
//        }
//
//        // Limpiar la selección de la tabla
//        jTable1.clearSelection();

    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
