package VIsta.Programa.Patrullajes;

public class Patrullajes_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Ptrullaje_Inicio
     */
    public Patrullajes_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDeletePatrullaje = new javax.swing.JButton();
        btnAddPatrullaje = new javax.swing.JButton();
        btnEditPatrullaje = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeletePatrullaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIsta/imagenes/btnDeleteP1.png"))); // NOI18N
        btnDeletePatrullaje.setBorderPainted(false);
        btnDeletePatrullaje.setContentAreaFilled(false);
        btnDeletePatrullaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePatrullaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletePatrullajeMouseClicked(evt);
            }
        });
        jPanel1.add(btnDeletePatrullaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 340, 60, 60));

        btnAddPatrullaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIsta/imagenes/btnAddP1.png"))); // NOI18N
        btnAddPatrullaje.setBorderPainted(false);
        btnAddPatrullaje.setContentAreaFilled(false);
        btnAddPatrullaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPatrullaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPatrullajeMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddPatrullaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 280, 60, 60));

        btnEditPatrullaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIsta/imagenes/btnEditP1.png"))); // NOI18N
        btnEditPatrullaje.setBorderPainted(false);
        btnEditPatrullaje.setContentAreaFilled(false);
        btnEditPatrullaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditPatrullaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditPatrullajeMouseClicked(evt);
            }
        });
        jPanel1.add(btnEditPatrullaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 220, 60, 60));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletePatrullajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePatrullajeMouseClicked

    }//GEN-LAST:event_btnDeletePatrullajeMouseClicked

    private void btnAddPatrullajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPatrullajeMouseClicked

    }//GEN-LAST:event_btnAddPatrullajeMouseClicked

    private void btnEditPatrullajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPatrullajeMouseClicked

    }//GEN-LAST:event_btnEditPatrullajeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddPatrullaje;
    private javax.swing.JButton btnDeletePatrullaje;
    private javax.swing.JButton btnEditPatrullaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
